# Generated by Django 2.1.1 on 2018-09-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPoblado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('nombre_cp', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
    ]
