# Generated by Django 2.1.1 on 2018-11-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaubigeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centropoblado',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
