# Generated by Django 2.1.1 on 2018-11-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapaubigeo', '0002_centropoblado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCentroPoblado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='centropoblado',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mapaubigeo.TipoCentroPoblado'),
        ),
    ]
