# Generated by Django 2.1.1 on 2018-11-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaubigeo', '0003_auto_20181119_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocentropoblado',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
