# Generated by Django 2.1.1 on 2018-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaubigeo', '0005_auto_20181119_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centropoblado',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'NO ES CAPITAL'), (1, 'DEPARTAMENTAL'), (2, 'PROVINCIAL'), (3, 'DISTRITAL')], default=0),
        ),
    ]
